#!/usr/bin/env node

import fs from "fs";

const commitMsgFile = process.argv[2];
const commitMsg = fs.readFileSync(commitMsgFile, 'utf8').trim();

const regex = /^(feat|fix|breaking)\s.+/;

if (!regex.test(commitMsg)) {
  console.error('The Given commit message does not follow commit message conventions!');
  process.exit(1); 
}

process.exit(0); 
